apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook-dev
resources:
  - ../../base 
patchesStrategicMerge:
  - deployment-patch.yml
commonLabels:
  environment: dev
images:
  - name: gcr.io/heptio-images/ks-guestbook-demo
    newTag: "0.2"