apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook-dev
resources:
- ../../base
images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newTag: "0.2"
labels:
- includeSelectors: true
  pairs:
    env: dev
patches:
- path: deployment-patch.yml
