apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook-staging
resources:
  - ../../base 
patches:
  - path: deployment-patch.yml
  - path: service-patch.yml
labels:
 - includeSelectors: true
   pairs:
      env: staging
images:
  - name: gcr.io/heptio-images/ks-guestbook-demo
    newTag: "0.2"